name: Super Circuit aggregation native_withdraw
on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened, labeled]
  schedule:
    - cron: '0 0 * * 6'

jobs:
  test:
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'ci-super-native-withdraw')
    uses: ./.github/workflows/circuit-test.yml
    with:
      circuit: super
      test-name: native_withdraw
      instance-type: x2iedn.24xlarge
      concurrency-group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.pull_request.number }}
    secrets: inherit
