name: Super Circuit aggregation eth_transfer
on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened, labeled]
  schedule:
    - cron: '0 0 * * 6'

jobs:
  test:
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'ci-super-eth-transfer')
    uses: ./.github/workflows/circuit-test.yml
    with:
      circuit: super
      test-name: eth_transfer
      instance-type: r6a.24xlarge
      concurrency-group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.pull_request.number }}
    secrets: inherit
